CREATE DATABASE BODEGA;

USE BODEGA;

CREATE TABLE PRODUCTOS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(28),
PRECIO FLOAT,
PROVEEDOR VARCHAR(28)
);

DESC PRODUCTOS;

SELECT * FROM PRODUCTOS;

INSERT INTO PRODUCTOS (NOMBRE, PRECIO, PROVEEDOR)
VALUES
("CAFE",3.99,"LUCKY_LUCAS_CA");

